version: '3.8'
services:
  backend:
    image: mouadhfersi/express-backend:latest
    container_name: backend
    ports:
      - "3001:3000"
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/myapp?authSource=admin
      - PORT=3000
      - NODE_ENV=production
    networks:
      - app-network
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    image: mouadhfersi/react-frontend:latest
    container_name: frontend
    ports:
      - "5173:80"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: myapp
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
