version: '3.8'

services:
  backend:
    image: mouadhfersi/express-backend:latest
    container_name: backend
    ports:
      - "3001:3000"  # Modifier le port d'exposition pour éviter le conflit
    environment:
      - MONGODB_URL=mongodb://mongo:27017/SkillsBridgePI
      - FRONTEND_URL=http://localhost:5173
    networks:
      - app-network
    depends_on:
      - mongo

  frontend:
    image: mouadhfersi/react-frontend:latest
    container_name: frontend
    ports:
      - "5173:80"  # Expose le frontend sur le port 5173
    networks:
      - app-network
    depends_on:
      - backend  # Le frontend dépend du backend

  mongo:
    image: mongo:latest  # Utilisation de MongoDB
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root  # Nom d'utilisateur root pour MongoDB
      MONGO_INITDB_ROOT_PASSWORD: example  # Mot de passe root pour MongoDB
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db  # Volume pour persister les données MongoDB
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
